# Generated by Django 6.0.8 on 2026-08-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#6366f1', help_text='HEX, masalan #0c4b33', max_length=7, verbose_name='Rang')),
            ],
            options={
                'verbose_name': 'Texnologiya',
                'verbose_name_plural': 'Texnologiyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=140, verbose_name='Sarlavha (uz)')),
                ('title_en', models.CharField(blank=True, max_length=140, verbose_name='Sarlavha (en)')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('summary_uz', models.CharField(max_length=220, verbose_name='Qisqa tavsif (uz)')),
                ('summary_en', models.CharField(blank=True, max_length=220, verbose_name='Qisqa tavsif (en)')),
                ('description_uz', models.TextField(verbose_name="To'liq tavsif (uz)")),
                ('description_en', models.TextField(blank=True, verbose_name="To'liq tavsif (en)")),
                ('cover', models.ImageField(blank=True, upload_to='projects/', verbose_name='Rasm')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub havolasi')),
                ('live_url', models.URLField(blank=True, verbose_name='Ishlayotgan sayt')),
                ('status', models.CharField(choices=[('planned', 'Rejada'), ('in_progress', 'Jarayonda'), ('done', 'Tugallangan')], default='done', max_length=20, verbose_name='Holati')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan (bosh sahifada)')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Boshlangan sana')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan")),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='projects.technology', verbose_name='Texnologiyalar')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_featured', 'order'], name='projects_pr_is_feat_a66c18_idx')],
            },
        ),
    ]
