# Generated by Django 6.0.8 on 2026-08-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, help_text="Rasm yuklanmagan bo'lsa, muqovada shu emoji chiqadi. Masalan: 🤖", max_length=8, verbose_name='Belgi (emoji)'),
        ),
    ]
