# Generated by Django 6.0.8 on 2026-08-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=160, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kelgan vaqti')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_uz', models.CharField(max_length=140, verbose_name="Yo'nalish (uz)")),
                ('degree_en', models.CharField(blank=True, max_length=140, verbose_name="Yo'nalish (en)")),
                ('institution_uz', models.CharField(max_length=140, verbose_name="O'quv muassasasi (uz)")),
                ('institution_en', models.CharField(blank=True, max_length=140, verbose_name="O'quv muassasasi (en)")),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (en)')),
                ('start_date', models.DateField(verbose_name='Boshlangan')),
                ('end_date', models.DateField(blank=True, help_text="Bo'sh = hozirgacha", null=True, verbose_name='Tugagan')),
                ('certificate_url', models.URLField(blank=True, verbose_name='Sertifikat havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Ta'lim",
                'verbose_name_plural': "Ta'lim",
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_uz', models.CharField(max_length=120, verbose_name='Lavozim (uz)')),
                ('role_en', models.CharField(blank=True, max_length=120, verbose_name='Lavozim (en)')),
                ('company', models.CharField(max_length=120, verbose_name='Tashkilot')),
                ('company_url', models.URLField(blank=True, verbose_name='Tashkilot sayti')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (en)')),
                ('start_date', models.DateField(verbose_name='Boshlangan')),
                ('end_date', models.DateField(blank=True, help_text="Bo'sh = hozirgacha", null=True, verbose_name='Tugagan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Tajriba',
                'verbose_name_plural': 'Tajriba',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name="To'liq ism")),
                ('headline_uz', models.CharField(max_length=160, verbose_name='Kasb (uz)')),
                ('headline_en', models.CharField(blank=True, max_length=160, verbose_name='Kasb (en)')),
                ('bio_uz', models.TextField(verbose_name='Men haqimda (uz)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Men haqimda (en)')),
                ('location_uz', models.CharField(blank=True, max_length=120, verbose_name='Manzil (uz)')),
                ('location_en', models.CharField(blank=True, max_length=120, verbose_name='Manzil (en)')),
                ('photo', models.ImageField(blank=True, upload_to='profile/', verbose_name='Rasm')),
                ('resume', models.FileField(blank=True, upload_to='resume/', verbose_name='CV fayli')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('website', models.URLField(blank=True, verbose_name='Shaxsiy sayt')),
                ('is_available', models.BooleanField(default=True, verbose_name='Ish takliflariga ochiq')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=80, verbose_name='Nomi (uz)')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='Nomi (en)')),
                ('icon', models.CharField(blank=True, max_length=8, verbose_name='Belgi (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Ko'nikma turkumi",
                'verbose_name_plural': "Ko'nikma turkumlari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, "Boshlang'ich"), (2, 'Asosiy'), (3, 'Ishonchli'), (4, 'Kuchli'), (5, 'Ekspert')], default=3, verbose_name='Daraja')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory', verbose_name='Turkum')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ['order', '-level', 'name'],
            },
        ),
    ]
