# Generated by Django 6.0.8 on 2026-08-13 14:30

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/', validators=[core.models.validate_upload_size], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Faqat PDF fayl qabul qilinadi.', upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf']), core.models.validate_upload_size], verbose_name='CV fayli (PDF)'),
        ),
    ]
