# Generated by Django 6.0.6 on 2026-08-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_photo_alter_profile_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('message', 'Yangi xabar'), ('resume', 'CV yuklab olindi'), ('error', 'Sayt xatosi'), ('spam', 'Spam urinishi'), ('info', "Ma'lumot")], default='info', max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(blank=True, verbose_name='Tafsilot')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Havola')),
                ('is_read', models.BooleanField(default=False, verbose_name="Ko'rilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='core_notifi_is_read_57d3f5_idx')],
            },
        ),
    ]
