# Generated by Django 6.0.6 on 2026-08-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='repeat_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Takrorlangan'),
        ),
    ]
