# Generated by Django 6.0.8 on 2026-08-12 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=160, verbose_name='Sarlavha (uz)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='Sarlavha (en)')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('excerpt_uz', models.CharField(max_length=250, verbose_name='Qisqa mazmun (uz)')),
                ('excerpt_en', models.CharField(blank=True, max_length=250, verbose_name='Qisqa mazmun (en)')),
                ('body_uz', models.TextField(verbose_name='Matn (uz)')),
                ('body_en', models.TextField(blank=True, verbose_name='Matn (en)')),
                ('cover', models.ImageField(blank=True, upload_to='blog/', verbose_name='Rasm')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Chop etilgan vaqti')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name="Ko'rishlar")),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='projects.technology', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='blog_post_publish_2c9212_idx')],
            },
        ),
    ]
