# Generated by Django 6.0.8 on 2026-08-13 14:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='blog/', validators=[core.models.validate_upload_size], verbose_name='Rasm'),
        ),
    ]
